version: "3.8"

services:
  process:
    image: ghcr.io/erfuuan/pulse-mq-panto/process:latest
    container_name: process
    ports:
      - "3000:3000"
    env_file:
      - .process.env
    restart: unless-stopped
    networks:
      - backend

  agent:
    image: ghcr.io/erfuuan/pulse-mq-panto/agent:latest
    container_name: agent
    env_file:
      - .agent.env
    restart: unless-stopped
    networks:
      - backend

  mongo:
    image: docker.arvancloud.ir/bitnami/mongodb
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  rabbitmq:
    image: docker.iranserver.com/bitnami/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
